package form.main;

import form.faktura.FakturaForm;
import form.student.StudentForm;
import controller.Controller;
import domain.Sluzbenik;
import form.smena.SmenaForm;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author lukas
 */
public class MainForm extends javax.swing.JFrame {

    private Sluzbenik ulogovaniSluzbenik;

    /**
     * Creates new form MainForma
     */
    public MainForm(Sluzbenik ulogovaniSluzbenik) {
        initComponents();

        this.ulogovaniSluzbenik = ulogovaniSluzbenik;

        stilizuj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovan = new javax.swing.JLabel();
        jLabelUlogovaniSluzbenik = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonUgasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelVreme = new javax.swing.JLabel();
        jLabelDobrodosli = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOperacije = new javax.swing.JMenu();
        jMenuItemFaktura = new javax.swing.JMenuItem();
        jMenuItemStudent = new javax.swing.JMenuItem();
        jMenuItemSmena = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUlogovan.setText("Ulogovan:");

        jLabelUlogovaniSluzbenik.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUlogovaniSluzbenik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUlogovaniSluzbenik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-wh.png"))); // NOI18N
        jLabelLogo.setText("jLabel2");

        jButtonUgasi.setText("Ugasi program");
        jButtonUgasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUgasiActionPerformed(evt);
            }
        });

        jLabel2.setText("Vreme:");

        jLabelVreme.setBackground(new java.awt.Color(0, 0, 0));
        jLabelVreme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelVreme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelDobrodosli.setText("Zdravo,");
        jLabelDobrodosli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuOperacije.setText("Operacije");

        jMenuItemFaktura.setText("Faktura odmora");
        jMenuItemFaktura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFakturaActionPerformed(evt);
            }
        });
        jMenuOperacije.add(jMenuItemFaktura);

        jMenuItemStudent.setText("Student");
        jMenuItemStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentActionPerformed(evt);
            }
        });
        jMenuOperacije.add(jMenuItemStudent);

        jMenuItemSmena.setText("Smena");
        jMenuItemSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSmenaActionPerformed(evt);
            }
        });
        jMenuOperacije.add(jMenuItemSmena);

        jMenuBar1.add(jMenuOperacije);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDobrodosli, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUlogovaniSluzbenik, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUgasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUgasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDobrodosli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUlogovaniSluzbenik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUlogovan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUgasiActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButtonUgasiActionPerformed
        try {
            Controller.getInstance().logout();
            System.exit(0);

        } catch (Exception ex) { 
            System.getLogger(MainForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }


    }//GEN-LAST:event_jButtonUgasiActionPerformed

    private void jMenuItemFakturaActionPerformed(
            java.awt.event.ActionEvent evt
    ) {
//GEN-FIRST:event_jMenuItemFakturaActionPerformed
        FakturaForm ff = new FakturaForm(this, true, ulogovaniSluzbenik);
        ff.setVisible(true);
    }//GEN-LAST:event_jMenuItemFakturaActionPerformed

    private void jMenuItemStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentActionPerformed
        StudentForm sf = new StudentForm(this, true);
        sf.setVisible(true);
    }//GEN-LAST:event_jMenuItemStudentActionPerformed

    private void jMenuItemSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSmenaActionPerformed
        SmenaForm sf = new SmenaForm(this, true);
        sf.setVisible(true);
    }//GEN-LAST:event_jMenuItemSmenaActionPerformed

    private void stilizuj() {
        this.setLocationRelativeTo(null);
        jLabelUlogovaniSluzbenik.setText(
                ulogovaniSluzbenik.getIme() + " " + ulogovaniSluzbenik.getPrezime()
        );
        jLabelDobrodosli.setText(
                "Zdravo, " + ulogovaniSluzbenik.getIme() + "!"
        );

        // Pozadina
        getContentPane().setBackground(new Color(0x1C2B3A));

        // Dugme Ugasi
        jButtonUgasi.setBackground(new Color(0xC0392B));
        jButtonUgasi.setForeground(Color.WHITE);
        jButtonUgasi.setFont(
                jButtonUgasi.getFont().deriveFont(java.awt.Font.BOLD, 14f)
        );
        jButtonUgasi.setCursor(
                new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
        );
        jButtonUgasi.putClientProperty("JButton.buttonType", "roundRect");
        jButtonUgasi.setOpaque(true);

        // Labele
        jLabelUlogovan.setForeground(Color.WHITE);
        jLabelUlogovan.setFont(
                jLabelUlogovan.getFont().deriveFont(java.awt.Font.BOLD, 14f)
        );
        jLabelUlogovaniSluzbenik.setForeground(new Color(0xE07B00));
        jLabelDobrodosli.setForeground(new Color(0xE07B00));
        jLabelDobrodosli.setFont(jLabelDobrodosli.getFont().deriveFont(java.awt.Font.BOLD, 18f));
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setFont(jLabel2.getFont().deriveFont(java.awt.Font.BOLD, 14f));
        jLabelVreme.setForeground(new Color(0xE07B00));

        // Timer za vreme
        Timer timer = new Timer(1000, e -> {
            LocalTime curTime = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(
                    "HH:mm:ss"
            );
            String formattedTime = curTime.format(formatter);
            jLabelVreme.setText(formattedTime);
        });
        timer.start();

        // Ikonica
        Icon i = jLabelLogo.getIcon();
        if (i instanceof ImageIcon) {
            ImageIcon icon = (ImageIcon) i;
            Image imageScale = icon
                    .getImage()
                    .getScaledInstance(144, 121, Image.SCALE_SMOOTH);
            jLabelLogo.setIcon(new ImageIcon(imageScale));
        }

        setTitle("Glavni meni");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUgasi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDobrodosli;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelUlogovan;
    private javax.swing.JLabel jLabelUlogovaniSluzbenik;
    private javax.swing.JLabel jLabelVreme;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemFaktura;
    private javax.swing.JMenuItem jMenuItemSmena;
    private javax.swing.JMenuItem jMenuItemStudent;
    private javax.swing.JMenu jMenuOperacije;
    // End of variables declaration//GEN-END:variables
}
